_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 80
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 80
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 64
learning_rate:
    value: 0.0001
num_epochs:
    value: 10
weight_decay:
    value: 1e-05
