# log dir 
log_dir: /home/ma/ma_ma/ma_tofuchs/Interpretable-Deep-Fake-Detection/logs/convnext

# model setting
pretrained: None #/pfs/work7/workspace/scratch/ma_tischuet-team_project_explainable_deepfakes/weights/convnext_best.pth # /home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/BWCluster/xception/logs/xception_2025-02-08-09-13-00/test/avg/ckpt_best.pth #/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/pretrained/xception-b5690688.pth   # path to a pre-trained model, if using one
model_name: convnext_bcos  # model name
backbone_name: convnext_bcos  # backbone name

#backbone setting
backbone_config:
  mode: original
  stochastic_depth_prob: 0.1  #could also be changed to match the block setting
  num_classes: 2
  layer_scale: 1e-5           # initial scaling factor for layer outputs
  # block setting set for tiny but should be changed every time 
  block_setting: tiny #stick with tiny for now and see if half decent results come out
  in_chans: 6
  # block: Optional[Callable[..., nn.Module]] = None
  # conv_layer: Callable[..., nn.Module] = DEFAULT_CONV_LAYER
  # norm_layer: Optional[Callable[..., nn.Module]] = None
#THESE LOGIT PARAMS DO NOT WORK RN - EXPLICITLY DEFINED AS NONE IN CODE
  logit_bias:  None 
  logit_temperature: None
  # **kwargs: Any


# dataset 
#all_dataset: #[df-tp-ffhq] #[FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT] #, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
#train_dataset: #[df-tp-ffhq] #[FaceForensics++]
#test_dataset: #[df-tp-ffhq] #[FaceForensics++] #, FF-F2F, FF-DF, FF-FS, FF-NT]

all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT] #, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [FaceForensics++]
test_dataset: [FaceForensics++] #, FF-F2F, FF-DF, FF-FS, FF-NT]

compression: c40  # compression-level for videos
train_batchSize: 64   # training batch size
test_batchSize: 64   # test batch size
workers: 8   # number of data loading workers
frame_num: {'train': 32, 'test': 32}   # number of frames to use per video in training and testing
resolution: 176   # resolution of output image to network
with_mask: false   # whether to include mask information in the input
with_landmark: false   # whether to include facial landmark information in the input
add_inverse_channels: true


# data augmentation
dataset_type: "bcos"
use_data_augmentation: false  # Add this flag to enable/disable data augmentation
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.0
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100

# mean and std for normalization
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

# optimizer config
optimizer:
  # choose between 'adam' and 'sgd'
  type: adam
  adam:
    lr: 0.001  # learning rate #orig: 0.0002
    beta1: 0.9  # beta1 for Adam optimizer
    beta2: 0.999 # beta2 for Adam optimizer
    eps: 0.00000001  # epsilon for Adam optimizer
    weight_decay: 0.0005  # weight decay for regularization
    amsgrad: false
  sgd:
    lr: 0.0002  # learning rate
    momentum: 0.9  # momentum for SGD optimizer
    weight_decay: 0.0005  # weight decay for regularization
  gradient_clipping: true

# training config
lr_scheduler: null   # learning rate scheduler
nEpochs: 60   # number of epochs to train for
start_epoch: 0   # manual epoch number (useful for restarts)
save_epoch: 1   # interval epochs for saving models
rec_iter: 100   # interval iterations for recording
logdir: ./logs   # folder to output images and logs
manualSeed: 1024   # manual seed for random number generation
save_ckpt: true   # whether to save checkpoint
save_feat: true   # whether to save features

# loss function
loss_func: cross_entropy   # loss function to use
losstype: null

# metric
metric_scoring: auc   # metric for evaluation (auc, acc, eer, ap)

# cuda

cuda: true   # whether to use CUDA acceleration
cudnn: true   # whether to use CuDNN for convolution operations
