# log dir 
log_dir: ./ #/home/ma/ma_ma/ma_tischuet/Interpretable-Deep-Fake-Detection/logs/resnet_v2

# model setting -> old
freeze: false
pretrained: #/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/pretrained/resnet_34-a63425a03e.pth
#/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/weights/ResNet34_Bcos_v2/resnet_34-a63425a03e.pth   # path to a pre-trained model, if using one
from_url: false
model_name: resnet34_bcos_v2   # model name
backbone_name: resnet34_bcos_v2  # backbone name

#backbone setting
backbone_config:
  num_classes: 2
  in_chans: 6
  #dropout: false
  #pretrained: false
  groups: 1
  base_width: 64
  zero_init_residual: false
  # replace_stride_with_dilation: None
  # norm_layer: None
  # short_cat: False
  # mode: Original
  small_inputs: false
  stochastic_depth_prob: 0.0
  logit_bias: #None
  logit_temperature: 1 #None
  b: 1.25
  norm: "BatchNormUncentered2d" # choices: AllNormUncentered2d, BatchNormUncentered2d, GroupNormUncentered2d, GNInstanceNormUncentered2d, GNLayerNormUncentered2d, 
  # PositionNormUncentered2d, AllNorm2d, BatchNorm2d, DetachableGroupNorm2d, DetachableGNInstanceNorm2d, DetachableGNLayerNorm2d, DetachableLayerNorm, DetachablePositionNorm2d
  norm_bias: false


# dataset
all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT,df-tp-ffhq] #, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [df-tp-ffhq]
test_dataset: [df-tp-ffhq] #, FF-F2F, FF-DF, FF-FS, FF-NT]
val_dataset: [df-tp-ffhq]

compression: c23  # compression-level for videos
train_batchSize: 64   # training batch size
val_batchSize: 64   # test batch size
test_batchSize: 64   # test batch size
workers: 8   # number of data loading workers
frame_num: {'train': 32, 'test': 32, 'val': 32}   # number of frames to use per video in training and testing
resolution: 256   # resolution of output image to network
with_mask: false   # whether to include mask information in the input
with_landmark: false   # whether to include facial landmark information in the input
save_ckpt: true   # whether to save checkpoint
save_feat: true   # whether to save features
add_inverse_channels: true
save_avg: true


# data augmentation
dataset_type: 'bcos'
use_data_augmentation: false  # Add this flag to enable/disable data augmentation
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100

# mean and std for normalization
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

# optimizer config
optimizer:
  # choose between 'adam' and 'sgd'
  type: adam
  adam:
    lr: 0.00028194716658124934  # learning rate
    beta1: 0.8786663327052217  # beta1 for Adam optimizer
    beta2: 0.9793096031838296 # beta2 for Adam optimizer
    eps: 0.00000755359342246203  # epsilon for Adam optimizer
    weight_decay: 0.00003994991349789046  # weight decay for regularization
    amsgrad: true
  sgd:
    lr: 0.0002  # learning rate, KAI: Lower LR may stabilize the results
    momentum: 0.9  # momentum for SGD optimizer
    weight_decay: 0.0005  # weight decay for regularization
  gradient_clipping: false

# training config
lr_scheduler: # step   # learning rate scheduler
#lr_eta_min: None
#lr_T_max: 65.82662824018384
#lr_step: 8
#lr_gamma: 0.11044395748175352
nEpochs: 20   # number of epochs to train for
start_epoch: 0   # manual epoch number (useful for restarts)
save_epoch: 1   # interval epochs for saving models
rec_iter: 100   # interval iterations for recording
logdir: ./logs   # folder to output images and logs
manualSeed: 10   # manual seed for random number generation

# loss function
loss_func: cross_entropy   # loss function to use
losstype: null

# metric
metric_scoring: auc   # metric for evaluation (auc, acc, eer, ap)

# cuda
ddp: false   # Kai: unnecessary, since it is overwritten anyway in train.py-> main() -> config['ddp']= args.ddp
cuda: true   # whether to use CUDA acceleration
cudnn: true   # whether to use CuDNN for convolution operations
