# log dir 
log_dir: /home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/logs/resnet_v2

# model setting -> old
freeze: false
pretrained: #/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/pretrained/resnet_34-a63425a03e.pth
#/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/weights/ResNet34_Bcos_v2/resnet_34-a63425a03e.pth   # path to a pre-trained model, if using one
from_url: false
model_name: vit_bcos   # model name
backbone_name: vit_bcos  # backbone name

#backbone setting
backbone_config:
  num_classes: 2
  channels: 6
  #dropout: false
  #pretrained: false
  #groups: 1
  #base_width: 64
  #zero_init_residual: false
  # replace_stride_with_dilation: None
  # norm_layer: None
  # short_cat: False
  # mode: Original
  #small_inputs: false
  #stochastic_depth_prob: 0.0
  logit_bias: #None
  logit_temperature: 1 #None
  b: 1.25
  image_size: 14 # Union[int, Tuple[int, int]],
  patch_size: 1 # Union[int, Tuple[int, int]],
  dim: 192
  depth: 11 # 12-1
  heads: 3
  mlp_dim: 768
  max_out: 1
  #linear_layer: Callable[..., nn.Module] = None,
  #norm_layer: Callable[..., nn.Module] = None,
  #act_layer: Callable[..., nn.Module] = None,
  #norm2d_layer: Callable[..., nn.Module] = None,
  #conv2d_layer: Callable[..., nn.Module] = None,
  conv_stem: [24, 48, 96, 192]

# dataset
all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT] #, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [FaceForensics++]
test_dataset: [FaceForensics++] #, FF-F2F, FF-DF, FF-FS, FF-NT]

compression: c40  # compression-level for videos
train_batchSize: 32   # training batch size
test_batchSize: 32   # test batch size
workers: 8   # number of data loading workers
frame_num: {'train': 32, 'test': 32}   # number of frames to use per video in training and testing
resolution: 224   # resolution of output image to network
with_mask: false   # whether to include mask information in the input
with_landmark: false   # whether to include facial landmark information in the input
save_ckpt: true   # whether to save checkpoint
save_feat: true   # whether to save features
add_inverse_channels: true


# data augmentation
dataset_type: 'bcos'
use_data_augmentation: false  # Add this flag to enable/disable data augmentation
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100

# mean and std for normalization
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

# optimizer config
optimizer:
  # choose between 'adam' and 'sgd'
  type: adam
  adam:
    lr: 0.0002  # learning rate
    beta1: 0.9  # beta1 for Adam optimizer
    beta2: 0.999 # beta2 for Adam optimizer
    eps: 0.00000001  # epsilon for Adam optimizer
    weight_decay: 0.0005  # weight decay for regularization
    amsgrad: false
  sgd:
    lr: 0.0002  # learning rate, KAI: Lower LR may stabilize the results
    momentum: 0.9  # momentum for SGD optimizer
    weight_decay: 0.0005  # weight decay for regularization
  gradient_clipping: true

# training config
lr_scheduler: warmup_cosine # step   # learning rate scheduler
lr_eta_min: 0
lr_T_max: 200
# lr_step: 4
# lr_gamma: 0.2
nEpochs: 15   # number of epochs to train for
start_epoch: 0   # manual epoch number (useful for restarts)
save_epoch: 1   # interval epochs for saving models
rec_iter: 100   # interval iterations for recording
logdir: ./logs   # folder to output images and logs
manualSeed: 1024   # manual seed for random number generation
save_ckpt: false   # whether to save checkpoint

# loss function
loss_func: cross_entropy   # loss function to use
losstype: null

# metric
metric_scoring: auc   # metric for evaluation (auc, acc, eer, ap)

# cuda
ddp: false   # Kai: unnecessary, since it is overwritten anyway in train.py-> main() -> config['ddp']= args.ddp
cuda: true   # whether to use CUDA acceleration
cudnn: true   # whether to use CuDNN for convolution operations
